"use server";

/**
 * Standalone invoice creation — founder request 2026-08-07: "under the
 * invoices tab, all invoices are generated from Quote however we need a new
 * invoice creation button in case we want to build an invoice from
 * scratch." Every OTHER invoice on this platform is generated by
 * lib/invoices/generate.ts's quote-driven functions
 * (generateDepositInvoiceForQuote/generateBalanceInvoiceForQuote), called
 * from the quote accept/customs-cleared workflow. This is the one entry
 * point that creates an invoice with no source quote at all
 * (lib/invoices/generate.ts's generateStandaloneInvoice, backed by
 * 20260807000003_standalone_invoices.sql's nullable quote_id).
 *
 * Called directly from the client form (not through a <form action> +
 * FormData) so a dynamic list of line items can be passed as a plain typed
 * array — the same pattern app/admin/projects/companyQuickCreate.ts's
 * createCompanyInline already uses for a client-called server action.
 */

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getCurrentUser } from "@/lib/auth";
import { generateStandaloneInvoice } from "@/lib/invoices/generate";
import { requireFounderAction } from "@/lib/roles/guards";

export type CreateStandaloneInvoiceLineInput = {
  description: string;
  qty: number;
  unitPriceJmd: number;
};

export type CreateStandaloneInvoiceResult =
  | { ok: true; invoiceId: string; error?: undefined }
  | { ok: false; error: string; invoiceId?: undefined };

export async function createStandaloneInvoice(
  companyId: string,
  projectId: string | null,
  lines: CreateStandaloneInvoiceLineInput[],
  dueNote: string | null,
): Promise<CreateStandaloneInvoiceResult> {
  let supabase;
  try {
    supabase = await createClient();
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : "Supabase is not configured." };
  }

  const user = await getCurrentUser();
  if (!user) return { ok: false, error: "You must be signed in to create an invoice." };

  const founderGate = await requireFounderAction("create an invoice");
  if (!founderGate.ok) return { ok: false, error: founderGate.error };

  const trimmedCompanyId = companyId.trim();
  if (!trimmedCompanyId) return { ok: false, error: "Choose a company." };

  const result = await generateStandaloneInvoice(
    supabase,
    {
      companyId: trimmedCompanyId,
      projectId: projectId?.trim() || null,
      lines: lines.map((l) => ({ description: l.description, qty: l.qty, unitPriceJmd: l.unitPriceJmd })),
      dueNote: dueNote?.trim() || null,
    },
    user.id,
  );

  if (!result.ok) return { ok: false, error: result.error };

  revalidatePath("/admin/invoices");
  redirect(`/admin/invoices/${result.invoice.id}`);
}
